// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.user_id", "045f1a29-9d4c-4ff0-b5a0-d5026a2ff49d");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1611931125);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1611931245);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1611930645);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1611930885);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1611930765);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1611931005);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1611930675);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1611931365);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 10249);
user_pref("browser.cache.disk.capacity", 389120);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.migration.version", 87);
user_pref("browser.newtabpage.activity-stream.impressionId", "{b36b0139-e327-404d-8e7e-465ce39439ac}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1611930662001");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1611932433001");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1611930621436");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1611952221436");
user_pref("browser.search.region", "KE");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1611930616");
user_pref("browser.startup.homepage_override.buildID", "20191210124657");
user_pref("browser.startup.homepage_override.mstone", "71.0");
user_pref("browser.startup.lastColdStartupCheck", 1611930616);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Yahoo!");
user_pref("distribution.iniFile.exists.appversion", "71.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 22 Jan 2021 23:33:01 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1611931127);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "71.0");
user_pref("extensions.lastPlatformVersion", "71.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"9f26cc4b-cd9e-4ae6-9c42-9f079167cade\",\"screenshots@mozilla.org\":\"f174e076-f382-4105-8366-fc3abde9c979\",\"webcompat-reporter@mozilla.org\":\"5ac208ce-0c00-45d6-88ee-34e59aecdd6a\",\"webcompat@mozilla.org\":\"9e251906-8138-4a8c-9e0c-1a680435bc49\",\"default-theme@mozilla.org\":\"10bb9aac-15b9-404a-8dfa-74d5b03d00e5\",\"yahoo@search.mozilla.org\":\"e73c9369-fe7a-4d1c-aca6-1b5a7a317f83\",\"startpage@search.mozilla.org\":\"ddfbb572-7855-41b9-9aba-2e9e54dda5ec\",\"duckduckgo@search.mozilla.org\":\"70952f38-dec0-476f-a354-5c0116dc38e9\",\"twitter@search.mozilla.org\":\"f2fcb1ac-d260-4b76-a365-e356ad8f70cb\",\"wikipedia@search.mozilla.org\":\"a3163e75-4c21-4628-93e2-bb01cb080a2f\"}");
user_pref("idle.lastDailyNotification", 1611931312);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1611931013);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20191210124657");
user_pref("media.gmp-manager.lastCheck", 1611931013);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1611931312);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "cd959677-b98c-4d6f-b81b-0b2b979a6d70");
user_pref("security.sandbox.plugin.tempDirSuffix", "9e4634ed-ff74-4240-9119-5f6d7c7459fd");
user_pref("services.settings.clock_skew_seconds", 10797);
user_pref("services.settings.last_etag", "\"1611907095284\"");
user_pref("services.settings.last_update_seconds", 1611920208);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1611920208);
user_pref("services.settings.main.cfr-fxa.last_check", 1611920208);
user_pref("services.settings.main.cfr.last_check", 1611920208);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1611920208);
user_pref("services.settings.main.hijack-blocklists.last_check", 1611920208);
user_pref("services.settings.main.language-dictionaries.last_check", 1611920208);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1611920208);
user_pref("services.settings.main.sites-classification.last_check", 1611920208);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1611920208);
user_pref("services.settings.main.whats-new-panel.last_check", 1611920208);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1611931312);
user_pref("toolkit.startup.last_success", 1611930612);
user_pref("toolkit.telemetry.cachedClientID", "c4af2689-cbd9-4d6d-ab28-e7bd062da288");
user_pref("toolkit.telemetry.previousBuildID", "20191210124657");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
